### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by gdave44** [RobertJN64/ESPHome-NTP-Server#1]
I just implemented your solution on a WT32-eth0 and it works great.
But, I had to add includes for <WiFi.h> and <WiFiUdp.h> for it to compile and run.

And, thank you SO much for your work!

**Comment by RobertJN64** [comment]
Thank you!

Can you submit a PR with the libraries added? I probably just always had them included as part of a different module.

**Comment by RobertJN64** [comment]
Perfect, thank you!
