### ISSUE TITLE
Not compile basic usage for esp8266

### ISSUE THREAD

**Issue by rudiyalex** [RobertJN64/ESPHome-NTP-Server#4]
Not compile basic usage for esp8266. (For esp32 compile good)

INFO ESPHome 2024.5.4
INFO Reading configuration /config/esphome/ntpserver.yaml...
INFO Detected timezone 'Europe/Kyiv'
INFO Generating C++ source...
INFO Compiling app...
Processing ntpserver (board: d1_mini; framework: arduino; platform: platformio/espressif8266@4.2.1)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
Dependency Graph
|-- ESPAsyncTCP-esphome @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.2.2
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- ArduinoJson @ 6.18.5
|-- TinyGPSPlus @ 1.0.2
Compiling .pioenvs/ntpserver/src/esphome/components/ntp_server/ntp_server.cpp.o
Compiling .pioenvs/ntpserver/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling .pioenvs/ntpserver/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
src/esphome/components/ntp_server/ntp_server.cpp:2:10: fatal error: WiFi.h: No such file or directory

**************************************************************
* Looking for WiFi.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:WiFi.h"
* Web  > https://registry.platformio.org/search?q=header:WiFi.h
*
**************************************************************

    2 | #include <WiFi.h>
      |          ^~~~~~~~
compilation terminated.
*** [.pioenvs/ntpserver/src/esphome/components/ntp_server/ntp_server.cpp.o] Error 1
========================== [FAILED] Took 4.98 seconds ==========================

**Comment by rudiyalex** [comment]
esphome:
  libraries:
    - SPI
    - wifi

**Comment by RobertJN64** [comment]
I updated the library to use the esphome wifi functions, fixing this issue. Thanks for pointing it out!
